### ISSUE TITLE
html -> lucid converter

### ISSUE THREAD

**Issue by vagifverdi** [chrisdone/lucid#16] opened 2015-02-06 20:10 UTC
Given html string output lucid code for it.

**Comment by chrisdone** [comment] 2015-02-06 22:21
This can probably easily be achieved with html-conduit.

**Comment by dbaynard** [comment] 2017-05-04 23:08
I've just adapted [jaspervdj/blaze-from-html](https://github.com/jaspervdj/blaze-from-html) for lucid, but I'm not sufficiently experienced with software licensing to judge what I'd need to do to publish it. With the blessing of @jaspervdj I'll upload to github.

Assuming that's all ok, it would benefit from a test suite. It should be able to maintain the invariant that rendering and parsing should return identical results, but there are perhaps plenty of edge cases.

**Comment by phadej** [comment] 2017-05-05 06:45
@dbaynard great! `blaze-from-html` is licenses as BSD3 (and GitHub is helpful to provide summaries: https://github.com/jaspervdj/blaze-from-html/blob/master/LICENSE) 

In short, if you also use BSD3, it's enough to credit Jasper (as it's lucid-from-html would be a fork / modified version of `blaze-from-html`). Luckily *BSD3* **doesn't** require to state what  exact modifications are made :)

**Comment by jaspervdj** [comment] 2017-05-05 11:42
@dbaynard I'm happy to give my blessing.  Please modify it however you want and upload it to github and hackage.

**Comment by dbaynard** [comment] 2017-05-05 14:24
It's at [dbaynard/lucid-from-html](https://github.com/dbaynard/lucid-from-html/tree/lucid).

I'm going to keep it on github for the moment. Once the test suite is running, and it's been battle tested a little, it may be worth adding as an executable to `lucid` itself. I've been working on another library using literate haskell (though with [markdown-unlit](https://hackage.haskell.org/package/markdown-unlit) i.e. fenced code blocks not bird tracks), and out of habit implemented this in a similar manner; so I would strip out the commentary if if is to integrate with `lucid`.

This was a quick and dirty conversion from `blaze-from-html`; in particular there are line-length issues, caused by the code generation being ad-hoc. If this is to be integrated into `lucid` I would prefer template-haskell style AST generation.

Anyway, thanks @jaspervdj, and please, give it a spin!

**Comment by phadej** [comment] 2017-05-05 14:34
@dbaynard do you generate some kind of simple AST which then is pretty-printed into code text, or how it works (sorry for being lazy to look into it).

**Comment by dbaynard** [comment] 2017-05-05 15:39
You joke about being lazy, but I didn't actually know, and had to check myself... there's a tree structure, but the pretty printing doesn't take into account line lengths (as far as I can tell) and my changes certainly don't take them into account.

I'll update the documentation of `lucid` to guide users to `lucid-from-html`. Would that suffice to close the issue, and I'll open a new one about integrating back into lucid?

**Comment by phadej** [comment] 2017-05-05 16:09
Let's open a new issue for the integration. A mention is good enough for now

**Closed** 2017-05-05 16:31 UTC
Labels: enhancement, help wanted

**Comment by DeepakKapiswe** [comment] 2024-04-03 06:46
Thanks @dbaynard It helped me a lot
